version: '3.9'

services:
  werewords-bot:
    build: .
    platform: linux/arm64
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
    volumes:
      - ./data:/app/data:ro
